- name: Copy containerd binary
  ansible.builtin.copy:
    src: "{{ containerd_binary }}"
    dest: "{{ containerd_binary_dest }}"
    mode: "0755"

- name: Copy containerd-shim-runc-v2 binary
  ansible.builtin.copy:
    src: "{{ containerd_binary | dirname }}/containerd-shim-runc-v2"
    dest: "{{ containerd_shim_binary_dest }}"
    mode: "0755"

- name: Copy runc binary
  ansible.builtin.copy:
    src: "{{ runc_binary }}"
    dest: "{{ runc_binary_dest }}"
    mode: "0755"

- name: Copy ctr binary
  ansible.builtin.copy:
    src: "{{ containerd_binary | dirname }}/ctr"
    dest: "{{ ctr_binary_dest }}"
    mode: "0755"

- name: Ensure containerd configuration directory exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Apply containerd configuration
  ansible.builtin.template:
    src: containerd-config.toml.j2
    dest: "{{ containerd_config }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart containerd

- name: Ensure containerd service file exists
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=containerd container runtime
      Documentation=https://containerd.io
      After=network.target

      [Service]
      ExecStart={{ containerd_binary_dest }} --config {{ containerd_config }}
      Restart=on-failure
      LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target
    dest: "{{ containerd_service }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart containerd

- name: Ensure containerd service is enabled and started
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
    state: started
