# Global paths
base_dir: /etc/kubernetes
pki_dir: "{{ base_dir }}/pki"
manifests_dir: "{{ base_dir }}/manifests"
config_dir: "{{ base_dir }}/configs"

# Binary paths (source from synced ansible/roles/*/files/)
cfssl_binary: /vagrant_data/ansible/roles/certificates/files/cfssl
cfssljson_binary: /vagrant_data/ansible/roles/certificates/files/cfssljson
etcd_binary: /vagrant_data/ansible/roles/etcd/files/etcd
etcdctl_binary: /vagrant_data/ansible/roles/etcd/files/etcdctl
kube_apiserver_binary: /vagrant_data/ansible/roles/control-plane/files/kube-apiserver
kube_controller_manager_binary: /vagrant_data/ansible/roles/control-plane/files/kube-controller-manager
kube_scheduler_binary: /vagrant_data/ansible/roles/control-plane/files/kube-scheduler
kubelet_binary: /vagrant_data/ansible/roles/kubelet/files/kubelet
kube_proxy_binary: /vagrant_data/ansible/roles/kube-proxy/files/kube-proxy
runc_binary: /vagrant_data/ansible/roles/container-runtime/files/runc
containerd_binary: /vagrant_data/ansible/roles/container-runtime/files/containerd
kubectl_binary: /vagrant_data/ansible/roles/networking/files/kubectl
flannel_manifest: /vagrant_data/ansible/roles/cni/files/kube-flannel.yml

# Kubernetes versions and settings
kubernetes_version: 1.34.1
etcd_version: 3.6.0
containerd_version: 2.0.0
cfssl_version: 1.6.5

# Network settings
pod_network_cidr: 10.244.0.0/16
service_cidr: 10.96.0.0/12
api_server_port: 6443
cluster_name: kubernetes

# System settings
swap_enabled: false
ntp_package: chrony
