- name: Apply RBAC
  ansible.builtin.command:
    cmd: "{{ kubectl_binary}} apply -f {{ rbac_config }}"
  changed_when: true

- name: Apply network policy
  ansible.builtin.command:
    cmd: "{{ kubectl_binary}} apply -f {{ network_policy }}"
  changed_when: true
