- name: Apply RBAC
  ansible.builtin.command:
    cmd: "kubectl apply -f {{ rbac_config }}"
  changed_when: true

- name: Apply network policy
  ansible.builtin.command:
    cmd: "kubectl apply -f {{ network_policy }}"
  changed_when: true
