# Global paths
base_dir: /etc/kubernetes
pki_dir: /var/lib/kubernetes
manifests_dir: "{{ base_dir }}/manifests"
config_dir: "{{ base_dir }}/configs"

# Certificate destination directories
certificate_dirs:
  kubernetes: "{{ pki_dir }}"
  etcd: /etc/etcd
  kubelet: "{{ pki_dir }}"
  kube_proxy: "{{ pki_dir }}"

# etcd settings
etcd_data_dir: /var/lib/etcd
etcd_cert_dir: "{{ certificate_dirs.etcd }}"

# Binary paths
etcd_binary: "{{ paths.artifacts.binaries }}/etcd"
etcdctl_binary: "{{ paths.artifacts.binaries }}/etcdctl"
kube_apiserver_binary: "{{ paths.artifacts.binaries }}/kube-apiserver"
kube_controller_manager_binary: "{{ paths.artifacts.binaries }}/kube-controller-manager"
kube_scheduler_binary: "{{ paths.artifacts.binaries }}/kube-scheduler"
kubelet_binary: "{{ paths.artifacts.binaries }}/kubelet"
kube_proxy_binary: "{{ paths.artifacts.binaries }}/kube-proxy"
runc_binary: "{{ paths.artifacts.binaries }}/runc"
containerd_binary: "{{ paths.artifacts.binaries }}/containerd"
kubectl_binary: "{{ paths.artifacts.binaries }}/kubectl"
flannel_manifest: "{{ paths.artifacts.manifests }}/kube-flannel.yml"

# Kubernetes versions and settings
kubernetes_version: 1.34.1
etcd_version: 3.6.0
containerd_version: 2.0.0

# Kubernetes API server addresses
kubernetes_public_address: "{{ network.masters[0].ip }}"
kubernetes_internal_address: 10.32.0.1

# Network settings
service_cidr: 10.96.0.0/12
api_server_port: 6443
api_server_endpoint: https://{{ kubernetes_public_address }}:6443
cluster_name: kubernetes

# System settings
swap_enabled: false
ntp_package: chrony

# Certificate settings
cert_key_size: 2048
cert_expiry: "8760h"

ssh_public_key_path: /home/vagrant/k8s-project/.vagrant/machines/jumpbox/virtualbox/private_key.pub
common_firewall_ports:
  - 22/tcp
  - 6443/tcp
  - 2379/tcp
  - 2380/tcp

cni_plugin: flannel
cni_manifest_paths:
  flannel: "{{ paths.artifacts.manifests }}/kube-flannel.yml"
  calico: "{{ paths.artifacts.manifests }}/calico.yaml"

cni_configs:
  flannel:
    pod_network_cidr: 10.244.0.0/16
  calico:
    pod_network_cidr: 192.168.0.0/16

pod_network_cidr: "{{ cni_configs[cni_plugin].pod_network_cidr }}"

cni_extra_ports:
  flannel:
    - 8472/udp
  calico:
    - 179/tcp
    - 4789/udp

paths:
  artifacts:
    base: "/home/vagrant/k8s-project/ansible/artifacts"
    binaries: "/home/vagrant/k8s-project/ansible/artifacts/binaries"
    certs: "/home/vagrant/k8s-project/ansible/artifacts/certs"
    kubeconfigs: "/home/vagrant/k8s-project/ansible/artifacts/kubeconfigs"
    manifests: "/home/vagrant/k8s-project/ansible/artifacts/manifests"
  kubernetes:
    pki_dir: "{{ pki_dir }}"
    config_dir: "{{ config_dir }}"
    manifests_dir: "{{ manifests_dir }}"
  etcd:
    cert_dir: "{{ certificate_dirs.etcd }}"
    data_dir: "{{ etcd_data_dir }}"
