# Control plane settings
kube_apiserver_bind_address: 0.0.0.0
kube_apiserver_port: "{{ api_server_port }}"
kube_apiserver_args:
  - --etcd-servers=https://192.168.56.11:2379
  - --etcd-cafile={{ pki_dir }}/ca.pem
  - --etcd-certfile={{ pki_dir }}/apiserver-etcd-client.pem
  - --etcd-keyfile={{ pki_dir }}/apiserver-etcd-client-key.pem
  - --client-ca-file={{ pki_dir }}/ca.pem
  - --service-account-key-file={{ pki_dir }}/sa.pub
  - --service-account-signing-key-file={{ pki_dir }}/sa-key.pem
  - --service-account-issuer=https://kubernetes.default.svc.cluster.local
  - --tls-cert-file={{ pki_dir }}/apiserver.pem
  - --tls-private-key-file={{ pki_dir }}/apiserver-key.pem
  - --service-cluster-ip-range={{ service_cidr }}
  - --encryption-provider-config={{ config_dir }}/encryption-config.yaml

kube_controller_manager_args:
  - --cluster-signing-cert-file={{ pki_dir }}/ca.pem
  - --cluster-signing-key-file={{ pki_dir }}/ca-key.pem
  - --service-account-private-key-file={{ pki_dir }}/sa-key.pem
  - --root-ca-file={{ pki_dir }}/ca.pem

kube_scheduler_args:
  - --authentication-kubeconfig={{ config_dir }}/kube-scheduler.kubeconfig
  - --authorization-kubeconfig={{ config_dir }}/kube-scheduler.kubeconfig
