paths:
  artifacts:
    base: "/home/vagrant/k8s-project/ansible/artifacts"
    binaries: "{{ paths.artifacts.base }}/binaries"
    certs: "{{ paths.artifacts.base }}/certs"
    kubeconfigs: "{{ paths.artifacts.base }}/kubeconfigs"
    manifests: "{{ paths.artifacts.base }}/manifests"
  kubernetes:
    pki_dir: "{{ pki_dir }}"
    config_dir: "{{ config_dir }}"
    manifests_dir: "{{ manifests_dir }}"
  etcd:
    cert_dir: "{{ certificate_dirs.etcd }}"
    data_dir: "{{ etcd_data_dir }}"
