- name: Ensure CNI manifest directory exists
  ansible.builtin.file:
    path: /etc/kubernetes
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: yes
  when: inventory_hostname == 'master1'
  tags: cni

- name: Apply CNI manifest
  ansible.builtin.command:
    cmd: kubectl --kubeconfig={{ cni_kubeconfig }} apply -f {{ cni_manifest_dest }}
  register: cni_apply
  changed_when: "'created' in cni_apply.stdout or 'configured' in cni_apply.stdout"
  when: inventory_hostname == 'master1'
  environment:
    KUBECONFIG: "{{ cni_kubeconfig }}"
  tags: cni
