- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Allow necessary ports
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item.split('/')[0] }}"
    proto: "{{ item.split('/')[1] if '/' in item else 'tcp' }}"
  loop: "{{ common_firewall_ports + (cni_extra_ports[cni_plugin] if cni_plugin in cni_extra_ports else []) }}"

- name: Enable ufw
  ansible.builtin.ufw:
    state: enabled
    policy: deny
