- name: Ensure SSH directory exists
  ansible.builtin.file:
    path: /home/ubuntu/.ssh
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0700"
  when: inventory_hostname in groups['masters'] or inventory_hostname in groups['workers'] or inventory_hostname == 'jumpbox'

- name: Deploy Vagrant SSH public key
  ansible.builtin.authorized_key:
    user: ubuntu
    state: present
    key: "{{ lookup('file', ssh_public_key_path) }}"
  when: inventory_hostname in groups['masters'] or inventory_hostname in groups['workers'] or inventory_hostname == 'jumpbox' and ssh_public_key_path is defined
  tags: ssh
