- name: Generate RBAC configuration
  ansible.builtin.template:
    src: rbac-hardening.yaml.j2
    dest: "{{ rbac_config }}"
    owner: root
    group: root
    mode: "0644"
  become: yes
  notify: Apply RBAC
  when: inventory_hostname == 'master1'
  tags: hardening
