- name: Ensure etcd backup directory exists
  ansible.builtin.file:
    path: "{{ etcd_backup_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  become: yes
  when: inventory_hostname in groups['etcd']
  tags: hardening

- name: Generate etcd backup script
  ansible.builtin.template:
    src: etcd-backup.sh.j2
    dest: "{{ etcd_backup_script }}"
    owner: root
    group: root
    mode: "0755"
  become: yes
  when: inventory_hostname in groups['etcd']
  tags: hardening

- name: Schedule etcd backup cron job
  ansible.builtin.cron:
    name: etcd-backup
    minute: "0"
    hour: "2"
    job: "{{ etcd_backup_script }}"
  become: yes
  when: inventory_hostname in groups['etcd']
  tags: hardening
