- name: Apply Flannel RBAC
  ansible.builtin.command:
    cmd: kubectl apply -f /etc/kubernetes/flannel-rbac.yaml
  register: flannel_rbac_apply
  changed_when: "'created' in flannel_rbac_apply.stdout or 'configured' in flannel_rbac_apply.stdout"
  environment:
    KUBECONFIG: "{{ config_dir }}/admin.kubeconfig"
  when: inventory_hostname == 'master1'
  tags: cni

- name: Restart kubelet for CNI
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
  become: yes
  when: inventory_hostname in groups['masters']
  tags: cni
