# ansible/roles/control-plane/handlers/main.yml
- name: Restart kube-apiserver
  ansible.builtin.systemd:
    name: kube-apiserver
    state: restarted

- name: Restart kube-controller-manager
  ansible.builtin.systemd:
    name: kube-controller-manager
    state: restarted

- name: Restart kube-scheduler
  ansible.builtin.systemd:
    name: kube-scheduler
    state: restarted


