- name: apply_coredns
  ansible.builtin.command:
    cmd: "kubectl --kubeconfig={{ config_dir }}/admin.kubeconfig apply -f {{ coredns_manifest }}"
  changed_when: true
  when: inventory_hostname == 'master1'
