- name: Copy etcd binary
  ansible.builtin.copy:
    src: "{{ etcd_binary }}"
    dest: "{{ etcd_binary_dest }}"
    mode: "0755"

- name: Copy etcdctl binary
  ansible.builtin.copy:
    src: "{{ etcdctl_binary }}"
    dest: "{{ etcdctl_binary_dest }}"
    mode: "0755"

- name: Ensure etcd data directory exists
  ansible.builtin.file:
    path: "{{ etcd_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Apply etcd configuration
  ansible.builtin.template:
    src: etcd.conf.j2
    dest: "{{ etcd_config }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart etcd
