- name: Copy all certificates to PKI directory
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - {src: "{{ role_path }}/files/ca.pem", dest: "{{ ca_pem }}", mode: "0644"}
    - {
        src: "{{ role_path }}/files/ca-key.pem",
        dest: "{{ ca_key_pem }}",
        mode: "0600",
      }
    - {
        src: "{{ role_path }}/files/kubernetes.pem",
        dest: "{{ kubernetes_pem }}",
        mode: "0644",
      }
    - {
        src: "{{ role_path }}/files/kubernetes-key.pem",
        dest: "{{ kubernetes_key_pem }}",
        mode: "0600",
      }
    - {
        src: "{{ role_path }}/files/admin.pem",
        dest: "{{ admin_pem }}",
        mode: "0644",
      }
    - {
        src: "{{ role_path }}/files/admin-key.pem",
        dest: "{{ admin_key_pem }}",
        mode: "0600",
      }
    - {
        src: "{{ role_path }}/files/kube-controller-manager.pem",
        dest: "{{ kube_controller_manager_pem }}",
        mode: "0644",
      }
    - {
        src: "{{ role_path }}/files/kube-controller-manager-key.pem",
        dest: "{{ kube_controller_manager_key_pem }}",
        mode: "0600",
      }
    - {
        src: "{{ role_path }}/files/kube-scheduler.pem",
        dest: "{{ kube_scheduler_pem }}",
        mode: "0644",
      }
    - {
        src: "{{ role_path }}/files/kube-scheduler-key.pem",
        dest: "{{ kube_scheduler_key_pem }}",
        mode: "0600",
      }
    - {
        src: "{{ role_path }}/files/kubelet.pem",
        dest: "{{ kubelet_pem }}",
        mode: "0644",
      }
    - {
        src: "{{ role_path }}/files/kubelet-key.pem",
        dest: "{{ kubelet_key_pem }}",
        mode: "0600",
      }
    - {
        src: "{{ role_path }}/files/service-account.pem",
        dest: "{{ service_account_pem }}",
        mode: "0644",
      }
    - {
        src: "{{ role_path }}/files/service-account-key.pem",
        dest: "{{ service_account_key_pem }}",
        mode: "0600",
      }

- name: Copy etcd certificates to etcd directory
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - {
        src: "{{ role_path }}/files/etcd.pem",
        dest: "{{ etcd_pem }}",
        mode: "0644",
      }
    - {
        src: "{{ role_path }}/files/etcd-key.pem",
        dest: "{{ etcd_key_pem }}",
        mode: "0600",
      }
  when: inventory_hostname in groups['etcd']
