- name: Download crictl binary with checksum
  get_url:
    url: "{{ download_urls.crictl.tarball }}"
    dest: "{{ paths.artifacts.binaries }}/crictl-v{{ versions.crictl }}-linux-amd64.tar.gz"
    mode: "0644"
    checksum: "{{ checksums.crictl.tarball }}"
    timeout: "{{ download_timeout }}"
  retries: "{{ download_retries }}"
  delegate_to: localhost

- name: Extract crictl tarball
  unarchive:
    src: "{{ paths.artifacts.binaries }}/crictl-v{{ versions.crictl }}-linux-amd64.tar.gz"
    dest: "{{ paths.artifacts.binaries }}"
    remote_src: yes
    creates: "{{ paths.artifacts.binaries }}/crictl"
  delegate_to: localhost

- name: Ensure crictl binary has correct permissions
  file:
    path: "{{ paths.artifacts.binaries }}/crictl"
    mode: "0755"
    owner: vagrant
    group: vagrant
  delegate_to: localhost
