- name: Setup artifact directories
  include: directory_setup.yml

- name: Download kubernetes binaries
  include: kubernetes_binaries.yml

- name: Download containerd binaries
  include: containerd_binaries.yml

- name: Download etcd binaries
  include: etcd_binaries.yml

- name: Download runc binaries
  include: runc_binaries.yml

- name: Download flannel and calico yaml files
  include: flannel_and_calico.yml

- name: Cleanup unncessary files
  include: cleanup.yml
