- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Allow necessary ports
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
    proto: "{{ item.split('/')[1] if '/' in item else 'tcp' }}"
  loop: "{{ common_firewall_ports }}"

- name: Enable ufw
  ansible.builtin.ufw:
    state: enabled
    policy: deny
