
- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: yes

- name: Ensure sysctl.conf template is applied
  ansible.builtin.template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload sysctl

- name: Ensure limits.conf template is applied
  ansible.builtin.template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure swap is disabled
  ansible.builtin.command:
    cmd: swapoff -a
  changed_when: false

- name: Comment out swap entries in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'

- name: Ensure chrony is installed
  ansible.builtin.apt:
    name: "{{ ntp_package }}"
    state: present

- name: Ensure chrony is enabled and started
  ansible.builtin.systemd:
    name: chrony
    enabled: yes
    state: started