- name: Ensure role directories exist
  ansible.builtin.file:
    path: "/home/vagrant/k8s-project/ansible/roles/{{ item }}/files"
    state: directory
    owner: vagrant # Match the vagrant user
    group: vagrant # Match the vagrant group
    mode: "0755" # Standard directory permissions (rwx for owner, rx for group/others)
  loop:
    - certificates-generate
    - etcd
    - control-plane
    - kubelet
    - kube-proxy
    - container-runtime
    - networking
    - cni
  when: inventory_hostname == 'jumpbox'
  become: yes # Need sudo to create directories as vagrant user
  become_user: vagrant

- name: Download binaries with correct executable permissions
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/home/vagrant/k8s-project/ansible/roles/{{ item.dest_dir }}/files/{{ item.filename }}"
    mode: "0755"
  loop:
    - {
        url: "https://github.com/cloudflare/cfssl/releases/download/v1.6.5/cfssl_1.6.5_linux_amd64",
        dest_dir: "certificates-generate",
        filename: "cfssl",
      }
    - {
        url: "https://github.com/cloudflare/cfssl/releases/download/v1.6.5/cfssljson_1.6.5_linux_amd64",
        dest_dir: "certificates-generate",
        filename: "cfssljson",
      }
    - {
        url: "https://github.com/etcd-io/etcd/releases/download/v3.6.0/etcd-v3.6.0-linux-amd64.tar.gz",
        dest_dir: "etcd",
        filename: "etcd.tar.gz",
        mode: "0644",
      }
    - {
        url: "https://dl.k8s.io/v1.34.1/bin/linux/amd64/kube-apiserver",
        dest_dir: "control-plane",
        filename: "kube-apiserver",
      }
    - {
        url: "https://dl.k8s.io/v1.34.1/bin/linux/amd64/kube-controller-manager",
        dest_dir: "control-plane",
        filename: "kube-controller-manager",
      }
    - {
        url: "https://dl.k8s.io/v1.34.1/bin/linux/amd64/kube-scheduler",
        dest_dir: "control-plane",
        filename: "kube-scheduler",
      }
    - {
        url: "https://dl.k8s.io/v1.34.1/bin/linux/amd64/kubelet",
        dest_dir: "kubelet",
        filename: "kubelet",
      }
    - {
        url: "https://dl.k8s.io/v1.34.1/bin/linux/amd64/kube-proxy",
        dest_dir: "kube-proxy",
        filename: "kube-proxy",
      }
    - {
        url: "https://github.com/opencontainers/runc/releases/download/v1.3.1/runc.amd64",
        dest_dir: "container-runtime",
        filename: "runc",
      }
    - {
        url: "https://github.com/containerd/containerd/releases/download/v2.1.4/containerd-2.1.4-linux-amd64.tar.gz",
        dest_dir: "container-runtime",
        filename: "containerd.tar.gz",
        mode: "0644",
      }
    - {
        url: "https://dl.k8s.io/v1.34.1/bin/linux/amd64/kubectl",
        dest_dir: "networking",
        filename: "kubectl",
      }
    - {
        url: "https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml",
        dest_dir: "cni",
        filename: "flannel.yml",
        mode: "0644",
      }
    - {
        url: "https://docs.projectcalico.org/manifests/calico.yaml",
        dest_dir: "cni",
        filename: "calico.yaml",
        mode: "0644",
      }
  when: inventory_hostname == 'jumpbox'

- name: Extract containerd archive
  ansible.builtin.unarchive:
    src: "/home/vagrant/k8s-project/ansible/roles/container-runtime/files/containerd.tar.gz"
    dest: "/home/vagrant/k8s-project/ansible/roles/container-runtime/files/"
    remote_src: yes
    owner: root
    group: root
  when: inventory_hostname == 'jumpbox'

- name: Extract etcd archive
  ansible.builtin.unarchive:
    src: "/home/vagrant/k8s-project/ansible/roles/etcd/files/etcd.tar.gz"
    dest: "/home/vagrant/k8s-project/ansible/roles/etcd/files/"
    remote_src: yes
    owner: root
    group: root
  when: inventory_hostname == 'jumpbox'

- name: Move containerd binaries to correct location
  ansible.builtin.shell: |
    cd /home/vagrant/k8s-project/ansible/roles/container-runtime/files/
    mv bin/* .
  when: inventory_hostname == 'jumpbox'

- name: Move etcd binaries to correct location
  ansible.builtin.shell: |
    cd /home/vagrant/k8s-project/ansible/roles/etcd/files/
  when: inventory_hostname == 'jumpbox'

- name: Set executable permissions on extracted binaries
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
  loop:
    - /home/vagrant/k8s-project/ansible/roles/container-runtime/files/containerd
    - /home/vagrant/k8s-project/ansible/roles/container-runtime/files/containerd-shim-runc-v2
    - /home/vagrant/k8s-project/ansible/roles/container-runtime/files/ctr
    - /home/vagrant/k8s-project/ansible/roles/etcd/files/etcd
    - /home/vagrant/k8s-project/ansible/roles/etcd/files/etcdctl
  when: inventory_hostname == 'jumpbox'

- name: Clean up containerd unnecessary files (preserve archives)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /home/vagrant/k8s-project/ansible/roles/container-runtime/files/bin
    - /home/vagrant/k8s-project/ansible/roles/container-runtime/files/containerd-stress
  when: inventory_hostname == 'jumpbox'
  become: yes

- name: Clean up etcd unnecessary files (preserve archives)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /home/vagrant/k8s-project/ansible/roles/etcd/files/etcd-v3.6.0-linux-amd64
    - /home/vagrant/k8s-project/ansible/roles/etcd/files/README-etcdctl.md
    - /home/vagrant/k8s-project/ansible/roles/etcd/files/README-etcdutl.md
    - /home/vagrant/k8s-project/ansible/roles/etcd/files/README.md
    - /home/vagrant/k8s-project/ansible/roles/etcd/files/READMEv2-etcdctl.md
    - /home/vagrant/k8s-project/ansible/roles/etcd/files/Documentation
    - /home/vagrant/k8s-project/ansible/roles/etcd/files/etcdutl
  when: inventory_hostname == 'jumpbox'
  become: yes

- name: Setup kubectl on jumpbox
  hosts: jumpboxes
  become: yes
  tasks:
    - include_tasks: ../roles/common/tasks/install_kubectl.yml
