- name: Generate CA certificate
  include_tasks: generate_ca.yml

- name: Generate admin client certificate
  include_tasks: generate_admin_cert.yml

- name: Generate controller certificates
  include_tasks: generate_controller_certs.yml

- name: Generate worker certificates
  include_tasks: generate_worker_certs.yml

- name: Generate service account key pair
  include_tasks: generate_service_account_key.yml

- name: Copy certificates to nodes
  include_tasks: copy_certs.yml
