# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

# Load network configuration from network.yml
network_config = YAML.load_file('ansible/inventory/group_vars/network.yml')

# Define resources
RESOURCES = {
  "master" => { "ram" => 2048, "cpu" => 2, "disk" => "50GB" },
  "worker" => { "ram" => 2048, "cpu" => 1, "disk" => "30GB" },
}
JUMP_RAM = 1024
JUMP_DISK = "20GB"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.ssh.insert_key = false

  # Jumpbox configuration
  config.vm.define "jumpbox" do |jumpbox|
    jumpbox.vm.network "private_network", ip: network_config['network']['jumpbox']['ip']
    jumpbox.vm.network "forwarded_port", guest: 22, host: 2731, id: "ssh"
    jumpbox.vm.hostname = network_config['network']['jumpbox']['name']
    jumpbox.vm.provider "virtualbox" do |vb|
      vb.memory = JUMP_RAM
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ['createhd', '--filename', './.vagrant/jumpbox-disk.vdi', '--size', 20 * 1024]
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', './.vagrant/jumpbox-disk.vdi']
    end
    jumpbox.vm.provision "shell", path: "provision_jumpbox.sh"
  end

  # Master nodes configuration
  network_config['network']['masters'].each_with_index do |master, index|
    config.vm.define master['name'] do |master_node|
      master_node.vm.network "private_network", ip: master['ip']
      master_node.vm.network "forwarded_port", guest: 22, host: 2711 + index, id: "ssh"
      master_node.vm.hostname = master['name']
      master_node.vm.provider "virtualbox" do |vb|
        vb.memory = RESOURCES["master"]["ram"]
        vb.cpus = RESOURCES["master"]["cpu"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ['createhd', '--filename', "./.vagrant/#{master['name']}-disk.vdi", '--size', 50 * 1024]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "./.vagrant/#{master['name']}-disk.vdi"]
      end
      master_node.vm.provision "shell", path: "provision_common.sh"
    end
  end

  # Worker nodes configuration
  network_config['network']['workers'].each_with_index do |worker, index|
    config.vm.define worker['name'] do |worker_node|
      worker_node.vm.network "private_network", ip: worker['ip']
      worker_node.vm.network "forwarded_port", guest: 22, host: 2721 + index, id: "ssh"
      worker_node.vm.hostname = worker['name']
      worker_node.vm.provider "virtualbox" do |vb|
        vb.memory = RESOURCES["worker"]["ram"]
        vb.cpus = RESOURCES["worker"]["cpu"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ['createhd', '--filename', "./.vagrant/#{worker['name']}-disk.vdi", '--size', 30 * 1024]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "./.vagrant/#{worker['name']}-disk.vdi"]
      end
      worker_node.vm.provision "shell", path: "provision_common.sh"
    end
  end
end
