- name: Copy kubectl binary
  ansible.builtin.copy:
    src: "{{ kubectl_binary }}"
    dest: "{{ kubectl_binary_dest }}"
    mode: "0755"

- name: Apply CoreDNS manifest
  ansible.builtin.template:
    src: coredns-deployment.yaml.j2
    dest: "{{ coredns_manifest }}"
    owner: root
    group: root
    mode: "0644"
  notify: Apply CoreDNS
  when: inventory_hostname == 'master1'

- name: Apply CoreDNS configuration
  ansible.builtin.command:
    cmd: "{{ kubectl_binary_dest }} apply -f {{ coredns_manifest }}"
  changed_when: true
  when: inventory_hostname == 'master1'
