- name: Apply CoreDNS manifest
  ansible.builtin.template:
    src: coredns-deployment.yaml.j2
    dest: "{{ coredns_manifest }}"
    owner: root
    group: root
    mode: "0644"
  notify: apply_coredns
  when: inventory_hostname == 'master1'

- name: Apply CoreDNS configuration
  ansible.builtin.command:
    cmd: "kubectl --kubeconfig={{ config_dir }}/admin.kubeconfig apply -f {{ coredns_manifest }}"
  changed_when: true
  when: inventory_hostname == 'master1'
