---
- name: Ensure kubeconfigs directory exists
  file:
    path: "{{ paths.artifacts.kubeconfigs }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: "0700"
  delegate_to: localhost

- name: Generate admin kubeconfig
  template:
    src: admin.kubeconfig.j2
    dest: "{{ paths.artifacts.kubeconfigs }}/admin.kubeconfig"
    mode: "0600"
    owner: vagrant
    group: vagrant
  delegate_to: localhost

- name: Generate kubelet kubeconfig per node
  template:
    src: kubelet.kubeconfig.j2
    dest: "{{ paths.artifacts.kubeconfigs }}/{{ item }}.kubeconfig"
    mode: "0600"
    owner: vagrant
    group: vagrant
  loop: "{{ groups['masters'] + groups['workers'] }}"
  delegate_to: localhost

- name: Generate kube-proxy kubeconfig
  template:
    src: kube-proxy.kubeconfig.j2
    dest: "{{ paths.artifacts.kubeconfigs }}/kube-proxy.kubeconfig"
    mode: "0600"
    owner: vagrant
    group: vagrant
  delegate_to: localhost

- name: Generate kube-scheduler kubeconfig
  template:
    src: kube-scheduler.kubeconfig.j2
    dest: "{{ paths.artifacts.kubeconfigs }}/kube-scheduler.kubeconfig"
    mode: "0600"
    owner: vagrant
    group: vagrant
  delegate_to: localhost

- name: Generate kube-controller-manager kubeconfig
  template:
    src: kube-controller-manager.kubeconfig.j2
    dest: "{{ paths.artifacts.kubeconfigs }}/kube-controller-manager.kubeconfig"
    mode: "0600"
    owner: vagrant
    group: vagrant
  delegate_to: localhost
