- name: Copy kube-proxy binary
  ansible.builtin.copy:
    src: "{{ kube_proxy_binary }}"
    dest: "{{ kube_proxy_binary_dest }}"
    mode: "0755"

- name: Apply kube-proxy configuration
  ansible.builtin.template:
    src: kube-proxy-config.yaml.j2
    dest: "{{ kube_proxy_config }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart kube-proxy

- name: Apply kube-proxy service template
  ansible.builtin.template:
    src: kube-proxy.service.j2
    dest: "{{ kube_proxy_service }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart kube-proxy

- name: Ensure kube-proxy service is enabled and started
  ansible.builtin.systemd:
    name: kube-proxy
    enabled: yes
    state: started
