- name: Ensure config directory exists on nodes
  file:
    path: "{{ paths.kubernetes.config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Distribute admin kubeconfig to masters
  copy:
    src: "{{ paths.artifacts.kubeconfigs }}/admin.kubeconfig"
    dest: "{{ paths.kubernetes.config_dir }}/admin.kubeconfig"
    mode: "0600"
    owner: root
    group: root
  when: inventory_hostname in groups['masters']
  retries: "{{ distribute_retries }}"

- name: Distribute kubelet kubeconfig to nodes
  copy:
    src: "{{ paths.artifacts.kubeconfigs }}/{{ inventory_hostname }}.kubeconfig"
    dest: "{{ paths.kubernetes.config_dir }}/kubelet.kubeconfig"
    mode: "0600"
    owner: root
    group: root
  when: inventory_hostname in groups['masters'] or inventory_hostname in groups['workers']
  retries: "{{ distribute_retries }}"

- name: Distribute kube-proxy kubeconfig to workers
  copy:
    src: "{{ paths.artifacts.kubeconfigs }}/kube-proxy.kubeconfig"
    dest: "{{ paths.kubernetes.config_dir }}/kube-proxy.kubeconfig"
    mode: "0600"
    owner: root
    group: root
  when: inventory_hostname in groups['workers']
  retries: "{{ distribute_retries }}"

- name: Distribute kube-scheduler kubeconfig to masters
  copy:
    src: "{{ paths.artifacts.kubeconfigs }}/kube-scheduler.kubeconfig"
    dest: "{{ paths.kubernetes.config_dir }}/kube-scheduler.kubeconfig"
    mode: "0600"
    owner: root
    group: root
  when: inventory_hostname in groups['masters']
  retries: "{{ distribute_retries }}"

- name: Distribute kube-controller-manager kubeconfig to masters
  copy:
    src: "{{ paths.artifacts.kubeconfigs }}/kube-controller-manager.kubeconfig"
    dest: "{{ paths.kubernetes.config_dir }}/kube-controller-manager.kubeconfig"
    mode: "0600"
    owner: root
    group: root
  when: inventory_hostname in groups['masters']
  retries: "{{ distribute_retries }}"
