- name: Create CA config file
  ansible.builtin.template:
    src: ca-config.json.j2
    dest: "{{ ca_config }}"
    mode: "0644"

- name: Create CA CSR file
  ansible.builtin.template:
    src: ca-csr.json.j2
    dest: "{{ ca_csr }}"
    mode: "0644"

- name: Create admin CSR file
  ansible.builtin.template:
    src: admin-csr.json.j2
    dest: "{{ admin_csr }}"
    mode: "0644"

- name: Create kubernetes CSR file
  ansible.builtin.template:
    src: kubernetes-csr.json.j2
    dest: "{{ kubernetes_csr }}"
    mode: "0644"

- name: Create kube-controller-manager CSR file
  ansible.builtin.template:
    src: kube-controller-manager-csr.json.j2
    dest: "{{ kube_controller_manager_csr }}"
    mode: "0644"

- name: Create kube-scheduler CSR file
  ansible.builtin.template:
    src: kube-scheduler-csr.json.j2
    dest: "{{ kube_scheduler_csr }}"
    mode: "0644"

- name: Create kubelet CSR file
  ansible.builtin.template:
    src: kubelet-csr.json.j2
    dest: "{{ kubelet_csr }}"
    mode: "0644"

- name: Create kube-proxy CSR file
  ansible.builtin.template:
    src: kube-proxy-csr.json.j2
    dest: "{{ role_path }}/files/kube-proxy-csr.json"
    mode: "0644"

- name: Create etcd CSR file
  ansible.builtin.template:
    src: etcd-csr.json.j2
    dest: "{{ etcd_csr }}"
    mode: "0644"

- name: Create service account CSR file
  ansible.builtin.template:
    src: service-account-csr.json.j2
    dest: "{{ service_account_csr }}"
    mode: "0644"
