- name: Generate CA certificate and key
  ansible.builtin.shell: "{{ cfssl_binary }} gencert -initca {{ ca_csr }} | {{ cfssljson_binary }} -bare ca"
  args:
    chdir: "{{ role_path }}/files"
    creates: "{{ role_path }}/files/ca.pem"
  when: not ansible_check_mode
  register: ca_generation_result
  failed_when: ca_generation_result.rc != 0

- name: Verify CA certificate was created
  ansible.builtin.stat:
    path: "{{ role_path }}/files/ca.pem"
  register: ca_cert_stat
  when: not ansible_check_mode
  failed_when: not ca_cert_stat.stat.exists

- name: Verify CA key was created
  ansible.builtin.stat:
    path: "{{ role_path }}/files/ca-key.pem"
  register: ca_key_stat
  when: not ansible_check_mode
  failed_when: not ca_key_stat.stat.exists
