- name: Generate kube-controller-manager certificate and key
  ansible.builtin.shell: "{{ cfssl_binary }} gencert -ca={{ role_path }}/files/ca.crt -ca-key={{ role_path }}/files/ca.key -config={{ ca_config }} -profile={{ ca_profile }} {{ kube_controller_manager_csr }} | {{ cfssljson_binary }} -bare kube-controller-manager"
  args:
    chdir: "{{ role_path }}/files"
    creates: "{{ role_path }}/files/kube-controller-manager.crt"
  when: not ansible_check_mode

- name: Generate kube-scheduler certificate and key
  ansible.builtin.shell: "{{ cfssl_binary }} gencert -ca={{ role_path }}/files/ca.crt -ca-key={{ role_path }}/files/ca.key -config={{ ca_config }} -profile={{ ca_profile }} {{ kube_scheduler_csr }} | {{ cfssljson_binary }} -bare kube-scheduler"
  args:
    chdir: "{{ role_path }}/files"
    creates: "{{ role_path }}/files/kube-scheduler.crt"
  when: not ansible_check_mode
