- name: Generate service account private key and CSR
  ansible.builtin.shell: "{{ cfssl_binary }} genkey {{ service_account_csr }} | {{ cfssljson_binary }} -bare sa"
  args:
    chdir: "{{ role_path }}/files"
    creates: "{{ role_path }}/files/sa-key.pem"
  when: not ansible_check_mode

- name: Extract service account public key from private key
  ansible.builtin.shell: "openssl rsa -in sa-key.pem -pubout -out sa.pub"
  args:
    chdir: "{{ role_path }}/files"
    creates: "{{ role_path }}/files/sa.pub"
  when: not ansible_check_mode
