- name: Generate service account certificate and key
  ansible.builtin.shell: "{{ cfssl_binary }} gencert -ca={{ role_path }}/files/ca.crt -ca-key={{ role_path }}/files/ca.key -config={{ ca_config }} -profile={{ ca_profile }} {{ service_account_csr }} | {{ cfssljson_binary }} -bare service-account"
  args:
    chdir: "{{ role_path }}/files"
    creates: "{{ role_path }}/files/sa.pub"
  when: not ansible_check_mode
