- name: Generate service account key pair
  ansible.builtin.shell: "{{ cfssl_binary }} gencert -ca={{ role_path }}/files/ca.pem -ca-key={{ role_path }}/files/ca-key.pem -config={{ ca_config }} -profile={{ ca_profile }} {{ service_account_csr }} | {{ cfssljson_binary }} -bare service-account"
  args:
    chdir: "{{ role_path }}/files"
    creates: "{{ role_path }}/files/service-account.pem"
  when: not ansible_check_mode
